### ISSUE TITLE
Minor Wording Issue in Fairness Audit Documentation

### ISSUE THREAD

**Issue by rgleaton** [epic-open-source/seismometer#107]
## Problem Summary
https://github.com/epic-open-source/seismometer/blob/8ae4df17b4a934227dc05fd2b3d923984032ed97/docs/user_guide/index.rst?plain=1#L229-L230

The text above is confusing and is likely meant to say "the context might explain" instead of "the context might that explains"

## Impact
Minor

## Possible Solution
Update wording of documentation

**Comment by firste** [comment]
Already fixed as part of #109
