### ISSUE TITLE
Create ability for Seismogram to start from_dataframe()

### ISSUE THREAD

**Issue by diehlbw** [epic-open-source/seismometer#20]
## Problem Summary
Currently the notebook requires the data to be in parquet format.  This is a good first step as it has implicit typing.  A logical next step is to accept the dataframe to already be loaded.

## Impact
Users may not have parquet files, and writing them just so they can be loaded is awkward (though has benefits on 'Restart and run all' situations).

## Possible Solution
Create a new class method from_dataframe that will expect the config file for data usage but will be passed the dataframe instead of loading from files.  

This will have implications on the default constructor as well; initial thoughts to be consistent would be moved to a 'from_parquet' method

**Comment by aurelienbono** [comment]
Hello I want to work on this issue 
I would like to have the documentation @diehlbw

**Comment by diehlbw** [comment]
Thanks for the offer!  I am actually getting very close to a working implementation on this, so I think the effort might be best directed to either other issues (I believe you have also started talking to Elliot) or expanding on the support after my next set of PRs.

To give an preliminary update, after some toying with options, I'm leaning toward a method for preloaded dataframes to be prioritized regardless of configuration while setting up a place for loaders to be more extensible to future sources.
