### ISSUE TITLE
Support boolean cohorts

### ISSUE THREAD

**Issue by TylerS99** [epic-open-source/seismometer#65]
## Is your feature request related to a problem? Please describe
When trying to import a cohort that is boolean (1/0) when running sm.run_startup() I receive the error TypeError: sequence item 0: expected str instance, bool found

## Describe the solution you'd like
If a cohort column is boolean, convert it to ['True', 'False'] on import.

## Describe alternatives you've considered
Considered modifying the SQL query to do this, but it would be easier if dtypes were handled in python.

**Comment by diehlbw** [comment]
So it looks like this wasn't a problem with the type of the cohort attribute, or not directly...

The TypeError: sequence item is raised during formulation of the warning about censoring.
Working on this fix now
