### ISSUE TITLE
Censor Limit Can Cause Crash When Logging if Cohort Isn't String

### ISSUE THREAD

**Issue by rgleaton** [epic-open-source/seismometer#69]
## Problem Summary
When some running startup, if some cohorts are below the censor threshold the code will attempt to log a message.

https://github.com/epic-open-source/seismometer/blob/37c691c0b6e78836fa3239f3c6395ca6a849a3fe/src/seismometer/seismogram.py#L370-L373

However, if the cohort values aren't string, such as in the case of Age (when not binned), this line will crash with the following error:
TypeError: sequence item 0: expected str instance, int found

## Impact
Crash

## Possible Solution
Cast to string when logging

## Steps to Reproduce
1. Have a cohort column that contains numeric data (such as age)
2. Make sure the cohort is below the censor limit
3. Try to run startup

**Comment by diehlbw** [comment]
Thanks for the report! 

This was the exact source of #65 and is fixed #68, which will move as soon as I get unit tests written around the methods.

**Comment by diehlbw** [comment]
Fixed by #68
